version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=achatdb
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork

  backend:
    image: backend
    depends_on:
      - mysqldb
    build: ./achat
    restart: on-failure
    ports:
      - 8082:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - ./m2:/root/.m2
    networks:
      - mynetwork

  node_exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    ports:
      - 9100:9100

networks:
  mynetwork:
    driver: bridge

volumes:
  db:
